spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/memo;
    username: sparta
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #      show_sql: true  => sysout으로 출력하기때문에 사용하지 않음
        format_sql: true